#!/bin/bash
trap "trap - SIGTERM && kill -- -$$" SIGINT SIGTERM EXIT

$HOME/.config/i3/xorg-config

$HOME/.config/i3/background-config &
picom &
/usr/lib/gsd-rfkill &
/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &

# dex -a
/usr/lib/xdg-desktop-portal-gtk &
/usr/lib/xdg-desktop-portal-wlr &

wait
