#!/bin/sh

# Start gnome-specific config daemons
/usr/lib/notification-daemon-1.0/notification-daemon      &
/usr/lib/gsd-xsettings                                    &
/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &
