#!/bin/sh
[ -z $1 ] && exit 1

GPG=`which gpg`
PASSWDDIR="$HOME/.config/passwd"
[ $PWD != $PASSWDDIR ] && cd $PASSWDDIR
FILENAME=`basename $1`.gpg
[ ! -f $FILENAME ] && exit 1

eval $($GPG -d $FILENAME)
