#!/bin/bash

get_color() {
    ps_salt="uuuuuuuuuuuuu"
    # ps_salt="manyshellcolors"

    ps_color="$((0x$( (echo "$ps_salt"; echo "$1") | sha256sum | cut -f1 -d' ' | tr -d '\n' | tail -c2)))"
    if [ "$ps_color" -le 10 ]; then
      ps_color="$((ps_color + 30))"
    fi
    if [ "$ps_color" -le 20 ]; then
      ps_color="$((ps_color + 10))"
    fi
    if [ "$ps_color" -gt 240 ]; then
      ps_color="$((ps_color - 20))"
    fi
    echo $ps_color
}

for i in home kratos ichebykin-nix aphrodite apollo athena demeter uranus; do
    ps_color="$(get_color "$i")"
    echo $ps_color
    echo -e "\e[38;5;${ps_color}m$i\e[0m"
done
