#!/bin/bash

DATA_DIR="$XDG_DATA_HOME"
[ -z "$DATA_DIR" ] && DATA_DIR="$HOME/.local/share"
CONF_DIR="$XDG_CONFIG_HOME"
[ -z "$CONF_DIR" ] && CONF_DIR="$HOME/.config"

UTIL_PATH="$CONF_DIR/i3/util"

KEEPER_UNIT="player-track-keeper"
TRACK_RESTORER_CMD="$UTIL_PATH/player-track-keeper.py restore-track"
LAST_ALBUM_FILE="$DATA_DIR/last-played-album"

LAST_ALBUM=""
[ -f "$LAST_ALBUM_FILE" ] && LAST_ALBUM="$(cat "$LAST_ALBUM_FILE")"

do_launch_player() {
    PLAYER="vlc"
    PLAYER_FLAGS="--no-playlist-autostart"
    if ! command -v "$PLAYER" >/dev/null 2>&1; then
        echo >&2 "No $PLAYER installed, exiting."
        exit 2
    fi
    album="$1"
    if [ ! -z "$album" ]; then
        album_path="$(realpath "$album")"
        if [ ! -e "$album_path" ]; then
            echo "$album_path: No such file or directory" 2>&1
            exit 2
        fi
        echo "$album_path" > "$LAST_ALBUM_FILE"
        echo "Launching player with: $album_path"
        nohup "$PLAYER" "$album_path" </dev/null >/dev/null 2>&1 &
        return
    fi
    if [ -z "$LAST_ALBUM" ]; then
        echo "No last played album was found. Specify new album manually." >&2
        exit 2
    fi
    echo "Launching player with: $LAST_ALBUM"
    nohup "$PLAYER" "$PLAYER_FLAGS" "$LAST_ALBUM" </dev/null >/dev/null 2>&1 &
    if systemctl --quiet --user is-active "$KEEPER_UNIT"; then
        systemctl --user stop "$KEEPER_UNIT"
    fi
    systemctl --user start "$KEEPER_UNIT"
    $TRACK_RESTORER_CMD
}

if [ ! -z "$1" ]; then
    case "$1" in
        launch) shift; do_launch_player "$@" ;;
        *) echo "Unknown command" >&2 ;;
    esac
fi
